-- GameLobbyClient.lua
-- DISABLED: Level selection is now handled by the Elevator Voting System.
-- Players must walk to an elevator pad to vote for a difficulty.
-- This script has been intentionally left blank to prevent duplicate UI.
